default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: task_rails_development

test:
  <<: *default
  database: task_rails_test

production:
  <<: *default
  database: task_rails_production
  username: task_rails
  password: <%= ENV['TASK_RAILS_DATABASE_PASSWORD'] %>
